### ISSUE TITLE
My button has missing

### ISSUE THREAD

**Issue by kajohnsakk** [TwoAbove/jsonschema-form-for-material-ui#12]
Can i show my button for submit form?

![screen shot 2562-03-06 at 3 54 11 pm](https://user-images.githubusercontent.com/43846278/53868222-254a3300-4028-11e9-9152-a3619fd5e191.png)

**Comment by TwoAbove** [comment]
Hello, @kajohnsakk! 
Do you have a onSubmit callback function passed? The cancel and submit buttons will not appear without the needed callback

**Comment by TwoAbove** [comment]
Closed due to inactivity
