### ISSUE TITLE
Props for material-UI components

### ISSUE THREAD

**Issue by ghost** [TwoAbove/jsonschema-form-for-material-ui#13]
Is it possible to give props for material-UI components from schema (or any other way)?

For example, setting InputLabelProps or variant etc.
![screenshot 2019-03-07 at 13 39 20](https://user-images.githubusercontent.com/16103245/53954327-977d4f00-40de-11e9-9337-69a9b2bf6a7e.png)

**Comment by TwoAbove** [comment]
Hey, @Hea7hcliff !
Currently only button props are supported. But it's pretty easy to do.
I'll be glad to see a pull request with the changes!

**Comment by TwoAbove** [comment]
Closed due to inactivity
