### ISSUE TITLE
How can I change the styling of the buttons for Add, Delete and re-order ?

### ISSUE THREAD

**Issue by samuelsunil** [TwoAbove/jsonschema-form-for-material-ui#14]
How can I change the styling of the buttons for Add, Delete and re-order ?

![image](https://user-images.githubusercontent.com/7824573/54309548-bed49000-45a6-11e9-885c-7b7eb3b8aafe.png)

**Comment by TwoAbove** [comment]
@SWORDFISH354 Pass the classes prop

**Comment by samuelsunil** [comment]
@TwoAbove  Thank you!

**Comment by TwoAbove** [comment]
@SWORDFISH354 
Just an FYI, it a standard thing in material UI. Look in their docs on styling
