### ISSUE TITLE
Formatting questions

### ISSUE THREAD

**Issue by anhlu8** [TwoAbove/jsonschema-form-for-material-ui#15]
Hi, I wrote a small app using your library and have some questions (I copied code to CodeSandbox: https://codesandbox.io/s/34mn3wj22p)

How do I set uiSchema for dropdown?
How do I go about validation?
Right now the startDate and endDate doesn't look right on the form.
Also, the library react-jsonschema-form offers onSubmit API so that when I click on button Submit, the data on the form will be logged out without me writing any code. How should I go about this with your library?

Any advice would be greatly appreciated!

**Comment by TwoAbove** [comment]
Hey, @anhlu8 Yes, this looks like a bug. It's an easy fix, but I'm not sure when I'll have the time to fix it. 
As a temporary workaround, you can pre-populate the field with a date (some logical one, like today's date or what fits more) 

Re `onSubmit` API, you can pass a callback prop to the library which returns the data

**Comment by TwoAbove** [comment]
@anhlu8 I'm deploying a new version (v1.4.1) that will have this issue fixed. Please check if it is and close this issue if all is good

**Comment by anhlu8** [comment]
@TwoAbove, it is fixed. Thank you very much!

**Comment by TwoAbove** [comment]
Glad to help!
