### ISSUE TITLE
The showHelperError attribute is ineffective

### ISSUE THREAD

**Issue by xuanzhiqiang** [TwoAbove/jsonschema-form-for-material-ui#18]
"jsonschema-form-for-material-ui": "^1.4.2"

![image](https://user-images.githubusercontent.com/20540666/58240260-3aa84100-7d7d-11e9-847b-df8eb99cd5bf.png)

![WeChat6746a3a32cf9e204c497ce682e083b30](https://user-images.githubusercontent.com/20540666/58240179-0cc2fc80-7d7d-11e9-8969-0648a1c16c98.png)

Version 1.4.2, `showHelperError={true}`  is ineffective

**Comment by xuanzhiqiang** [comment]
Hi, @TwoAbove 
    Please help me

**Comment by TwoAbove** [comment]
Hey, @xuanzhiqiang ! 
Sorry for the late reply. 
I'm waiting for a resolution of https://github.com/mozilla-services/react-jsonschema-form/issues/1222 to re-write a big chunk of this repo (as a v2?). 

I'm not sure what the issue is, because the errors are shown on top. Can you explain?
