### ISSUE TITLE
Migration to withTheme API.

### ISSUE THREAD

**Issue by Fedorov113** [TwoAbove/jsonschema-form-for-material-ui#19]
Hello! What's the plan for migration to the new `withTheme` API? I am willing to help, but I need your guidance.

**Comment by TwoAbove** [comment]
Hey @Fedorov113 !

I'll plan it out when I get home. 
Expect issues with `help needed` on them.

It will be mostly transferring to json schema form instead of Homebrew, so easily paralleled

**Comment by TwoAbove** [comment]
@Fedorov113 
https://github.com/TwoAbove/jsonschema-form-for-material-ui/blob/v2/README.md
I've created a `v2` branch. All PRs related to the re-write will go there. I'll create issues when I have the time (today-tomorrow'ish)
