### ISSUE TITLE
Apply attributes from Material-ui

### ISSUE THREAD

**Issue by jmmccota** [TwoAbove/jsonschema-form-for-material-ui#8]
Hello,

There is a way to apply Material-ui attributes into components, like **color="primary"** and **variant="outlined"** into buttons and fields?

Thanks a lot!

**Comment by TwoAbove** [comment]
Hey, @jmmccota !
Sorry for the late reply. 
Not as of yet. I'll put it on the to-do list. 

If you have 15 minutes, you can add it yourself: just need to pass in extra props into `FormButtons` in `src/Form.jsx`

Thanks for your contribution!

**Comment by TwoAbove** [comment]
Hey, @jmmccota !
Updated the project to v.1.4.0

Added `buttonProps` to the main props list. Use it like mui's variant: 
```js
buttonProps={{
    variant: 'text'
}}
```
and so on. This will propagate into the form button11s.
Refer to GH-11 for more info
