### ISSUE TITLE
The labels overlap with text boxes when there is initial form data

### ISSUE THREAD

**Issue by aramkoukia** [TwoAbove/jsonschema-form-for-material-ui#9]
The labels overlap with text boxes when there is initial form data
Initial form load looks like this:
![image](https://user-images.githubusercontent.com/7307404/52761339-daf50980-2fc7-11e9-9660-143855fdbb88.png)

When I focus on the text boxes, the label moves up a bit and looks good. also if I edit the text value even if I change it back to the original value, still looks good
Issue happens on the initial load before user touches anything
![image](https://user-images.githubusercontent.com/7307404/52761387-14c61000-2fc8-11e9-9588-9e6c88f74c79.png)

**Comment by TwoAbove** [comment]
Hey, @aramkoukia !
This is a known bug in material-ui itself. I'll take a look tomorrow and check if there is a fix for it

**Comment by aramkoukia** [comment]
Thanks @TwoAbove 
Looks like this issue that is closed:
https://github.com/mui-org/material-ui/issues/13186

**Comment by TwoAbove** [comment]
@aramkoukia Yep, and just in case I'll update all deps and default to an empty string in inputs

**Comment by TwoAbove** [comment]
Hey, @aramkoukia !
Updated project to 1.4.0

Updated the packages and no error occured for me (if it still does, please open a new issue with code to reproduce)
Refer to GH-11 for more info

**Comment by aramkoukia** [comment]
Yes, it works perfect with 1.4.0
Thanks a lot @TwoAbove, you rock! 🙌 🙌
